### ISSUE TITLE
Slower Code on Parallelization

### ISSUE THREAD

**Issue by aaronjs99** [BitJetKit/Monte_Carlo_OpenMP#1]
I got the following results:

![JonKelly](https://user-images.githubusercontent.com/38135463/108607803-a30bd280-73e8-11eb-9089-e3c979ca10bd.png)

Can you verify the same? It seems a bit non-intuitive that parallelization causes the code to run 10 times slower. I'm running the exact code as provided in Pi.c

**Comment by BitJetKit** [comment]
Hello aaronjohnsabu1999,

Thank you for checking my work: good question! And I apologize for the long wait.

I duplicated your work, and I displayed an output like my original runs output during my undergraduate program at Regent University in CSCI 322 (Distributive and Parallel Programming). During my undergraduate program, I had a comparable system, but I believe it was a quad core, and I relied on its CPU. For performance like my undergraduate program's, the following terminal command compiles this software app:

`gcc -o omp_pic -fopenmp OpenMP.c
`  
And the following command can run this software app like my undergraduate program's performance:
`./omp_pic 5000000`
Below, you can see your commands duplicated, but I also displayed my performance like my undergraduate program. The following is this software app at work:
![OpenMP Pi on Ubuntu on Windows](https://user-images.githubusercontent.com/12926868/112241276-ef307980-8c17-11eb-9226-2a0f460eb701.png)
As you can see, more threads take longer. But how? 

Without having your rig's exact specifications, comparing your rig to mine is difficult, but I have an AMD Ryzen 3 3250U, now ([link](https://www.amd.com/en/products/apu/amd-ryzen-3-3250u)). On Stack Exchange's UNIX and Linux section: nearing 1 decade ago, a user named frostschutz gave an excellent response to this very question ([link](https://unix.stackexchange.com/questions/80424/why-using-more-threads-makes-it-slower-than-using-less-threads#:~:text=Having%20fewer%20threads%20would%20not,fighting%20over%20the%20CPU%20resource.&text=On%20a%20single%20core%20CPU,faster%20than%20any%20threading%20done.)). Basically, an optimized processing speed has threads equal to cores. With OpenMP and any parallel programming, you can maximize a thread to core balance: use a GPU. Therefore, an optimized thread to cores ratio is intuitive because it is a relation.

Regards,
Bit Jet Kit

**Comment by aaronjs99** [comment]
Hi BitJetKit,

No issues. I eventually wrote a new code for the same which didn't work super-well but enough for the need of the day...

I had a 2-core 4-thread system back then. I guess @frostschutz's answer makes sense since I never cared to stop other programs while testing... Yeah, probably all this overhead usage made the multi-threaded program slower.

Thanks for the reply!
